name: Run unit tests

on:
  pull_request:
  push:
    branches:
    - master
  workflow_dispatch:
  schedule:
    # Run every Sunday at 03:53 UTC
    - cron: 13 3 * * 0

jobs:
  tests:
    name: ${{ matrix.os }}, ${{ matrix.tox_env }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.7'
            tox_env: 'check'
          - os: ubuntu-latest
            python-version: '3.7'
            tox_env: 'py37'
            tox_args: '--pyargs mpdaf'
          - os: ubuntu-latest
            python-version: '3.8'
            tox_env: 'py38'
            tox_args: '--pyargs mpdaf'
          - os: ubuntu-latest
            python-version: '3.8'
            tox_env: 'py38'
            tox_args: '-sv --runslow lib/mpdaf/sdetect/tests/test_muselet.py'
          - os: ubuntu-latest
            python-version: '3.9'
            tox_env: 'py39'
            tox_args: '--pyargs mpdaf --remote-data=any'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install SExtractor
      run: sudo apt-get install sextractor
    - name: Install Tox
      run: python -m pip install tox coverage
    - name: Run Tox
      run: tox -e ${{ matrix.tox_env }} -- ${{ matrix.tox_args }}
    - name: Convert coverage
      run: python -m coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
